packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  core-js: true
  es5-ext: false
  esbuild: true
  leveldown: false
  protobufjs: false

overrides:
  prosemirror-model: 1.25.11

patchedDependencies:
  tiptap-pagination-plus@3.1.0: patches/tiptap-pagination-plus@3.1.0.patch
