packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  '@percy/core': false
  core-js: true
  esbuild: true
  leveldown: false
  mongodb-memory-server: true
  protobufjs: false
  puppeteer: true

overrides:
  prosemirror-model: 1.25.11
