packages:
  - 'packages/*'
allowBuilds:
  '@percy/core': false
  core-js: true
  es5-ext: false
  esbuild: true
  leveldown: false
  mongodb-memory-server: true
  protobufjs: false
  puppeteer: true

overrides:
  prosemirror-model: 1.25.11

patchedDependencies:
  tiptap-pagination-plus@3.1.0: patches/tiptap-pagination-plus@3.1.0.patch
