import './styles/index.css'

export { useEditor, type UseEditorOptions, type UseEditorReturn } from './composables/useEditor.js'
export { useTheme } from './composables/useTheme.js'
export { default as DocsEditor } from './components/DocsEditor.vue'
export { default as EditorToolbar } from './components/EditorToolbar.vue'
export { default as PageView } from './components/PageView.vue'
export { default as HeaderBar } from './components/HeaderBar.vue'
export { default as StatusBar } from './components/StatusBar.vue'
export { default as BubbleMenu } from './components/BubbleMenu.vue'
export { default as ThemeToggle } from './components/ThemeToggle.vue'
export { default as AISidebar } from './components/sidebars/AISidebar.vue'
export { default as CommentsSidebar } from './components/sidebars/CommentsSidebar.vue'
export { default as HistorySidebar } from './components/sidebars/HistorySidebar.vue'
export { default as TOCSidebar } from './components/sidebars/TOCSidebar.vue'
export { default as DocumentTabsSidebar } from './components/DocumentTabsSidebar.vue'
export { default as SlashMenu } from './components/SlashMenu.vue'
export type * from './types.js'
